var aiServiceHandler = require('./handlers/ai');
var layoutServiceHandler = require('./handlers/layout');
var generatorServiceHandler = require('./handlers/generator');
const CONFIG = require('./../config');
const path = require('path');
const fs = require('fs');
const rimraf = require("rimraf");

/**
 * Writes data to update current page as last page created by idea2life.
 * @param pagename - name of the page
 * @param saved - whether this page needs to be saved
 */
function writeLastUserPageData(pagename, saved=false){

    var data_filepath = path.join(__dirname, '../', CONFIG.utilities.last_page_data.root_dir, 
    CONFIG.utilities.last_page_data.filename);

    var json_file = fs.readFileSync(data_filepath);
    var json_data = JSON.parse(json_file);

    if (saved){
        json_data[CONFIG.utilities.last_page_data.name_key] = null;
    }
    else{
        json_data[CONFIG.utilities.last_page_data.name_key] = pagename;
    }

    fs.writeFile(data_filepath, JSON.stringify(json_data), 'utf-8', function(err){

        if (err){
            
            console.log(" Could not write last exported json file");
        }
        else {
            console.log(" Succesfully stored the exported file in a json");
        }
    });
}

/**
 * Deletes the page not saved by the user.
 */
function deleteLastUserPageFolder(){

    var json_file = fs.readFileSync(path.join(__dirname, '../', CONFIG.utilities.last_page_data.root_dir, 
    CONFIG.utilities.last_page_data.filename));
    var json_data = JSON.parse(json_file);

    if (json_data[CONFIG.utilities.last_page_data.name_key] !== null){

        var foldername = json_data[CONFIG.utilities.last_page_data.name_key];
        var folderpath = path.join(__dirname, "../", CONFIG.server.path_for_static.userdata, foldername.toString());

        // check if this folder exist
        if (fs.existsSync(folderpath)){

            // delete the folder
            rimraf(folderpath, function (err) {

                if (!(err)){
                    
                    console.log("folder ", folderpath , " deleted");

                }
                
            });
        }
    }
}

/**
 * The core function of the UI which transmits data from one service to another to
 * generate the html result.
 * @param req - request object.
 * @param res - response object.
 * @param base64Image - base64 image clicked by the idea2life.
 * @param filename - default filename generated by system (unix timestamp)
 * @throws {object} If any error is encountered, the erorr received is of the format
 *  { data: erroData, category: 'error', msg: 'Error Message', title: 'Service/ Module Name'}
 * @returns {string} serialized html data generated for the image clicked.
 */
function main(req, res, base64Image, filename){

    // sends image to AI service
    aiServiceHandler.sendImageToAIService(res, base64Image, filename, function(aiData){

        var layoutData = {
            componentsData : aiData.data.results,
            imageHeight: aiData.data.height,
            imageWidth: aiData.data.width, 
            filename: filename
        };

        // sends AI data to layout service
        layoutServiceHandler.sendAIDataToLayoutService(res, layoutData, function(xmlData){

            var generatorData = {
                xml : xmlData,
                filename: filename
            };
            
            // sends layout XML data to generator service which generates page based on theme
            generatorServiceHandler.sendXMLToGeneratorService(res, generatorData, function(data){

                // delete existing page
                deleteLastUserPageFolder();

                // write new name
                writeLastUserPageData(filename);

                // send response back to the ui
                res.send(JSON.stringify(data));
            });
        });
    });
}


module.exports.utilities = {
    main: main,
    setLastUserDetails: writeLastUserPageData
};